/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2021-11-23 03:40:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import co.jp.netwisdom.entity.UserinfoAndHobby;

public final class UserSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t");
 UserinfoAndHobby uahEntity = (UserinfoAndHobby)request.getAttribute("uahEntity");
      out.write('\r');
      out.write('\n');
      out.write('	');
 String hobby = (String)request.getAttribute("hobby");
      out.write("\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>用户检索页面</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
 if(uahEntity != null && hobby != null){
      out.write("\r\n");
      out.write("\t\t<form action=\"usersearch\" method=\"get\">\r\n");
      out.write("\t姓名:<input type = \"text\" name = \"name\" id = \"name\" value = \"");
      out.print(uahEntity.getUsername() );
      out.write("\"/><br>\r\n");
      out.write("\t性别:<input type = \"radio\" name=\"sex\" id =\"sex\" value=\"0\" ");
      out.print(uahEntity.getSex().equals("0")? "checked" : "");
      out.write(">男\r\n");
      out.write("\t\t<input type = \"radio\" name=\"sex\" id =\"sex\" value=\"1\" ");
      out.print(uahEntity.getSex().equals("1")? "checked" : "");
      out.write(">女<br>\r\n");
      out.write("\t爱好:<input type=\"checkbox\" name=\"hobby\" id=\"hobby\" value=\"0\" ");
      out.print(hobby.contains("0")? "checked" : "" );
      out.write(">篮球\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"hobby\" id=\"hobby\" value=\"1\" ");
      out.print(hobby.contains("1")? "checked" : "" );
      out.write(">足球\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"hobby\" id=\"hobby\" value=\"2\" ");
      out.print(hobby.contains("2")? "checked" : "" );
      out.write(">网球\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t专业:<select name=\"major\" id=\"major\">\r\n");
      out.write("\t\t\t<option value=\"0\" ");
      out.print(uahEntity.getMajor().equals("0")? "selected" : "" );
      out.write(">软件工程</option>\r\n");
      out.write("\t\t\t<option value=\"1\" ");
      out.print(uahEntity.getMajor().equals("1")? "selected" : "" );
      out.write(">英语</option>\r\n");
      out.write("\t\t\t<option value=\"2\" ");
      out.print(uahEntity.getMajor().equals("2")? "selected" : "" );
      out.write(">数学</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t<input type=\"submit\" value =\"检索\">\r\n");
      out.write("\t<input type=\"reset\" value =\"重置\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
 }
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<hr>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
